### ISSUE TITLE
Why Pygments Dependancy?

### ISSUE THREAD

**Issue by ghost** [aaronkwhite/foundation-jekyll#2]
I can't get up and running. Jekyll will not build the site. I am running Mac OS X El Cap and have installed Pygments via Python command. But it will not build out the site. Hope this helps others.

**Comment by aaronkwhite** [comment]
Pygments is used for syntax highlighting, which isn't always required for most projects. I'll comment out that line and it should help in the future.

**Comment by aaronkwhite** [comment]
This has been addressed with: 
https://github.com/aaronkwhite/foundation-jekyll/commit/6786f5ce9f20c6d4e9736657b9889e2c3003ce3d
